#!/usr/bin/env python3
"""Compare CMASS log-probability values and timings against ``main``.

The current refactor changed both the public runtime API and the input data
contract.  This harness keeps the comparison honest by running each branch in
its own Python subprocess with an isolated ``PYTHONPATH``:

* ``main`` uses its historical ``cmass_lens_inference.model`` entrypoint and
  raw observation/cross-section files.
* the candidate worktree uses
  ``cmass_lens_inference.numba_backend.likelihood_engine`` and a canonical
  inference dataset generated from the same synthetic scientific content.

Only the small synthetic CMASS/Sersic case is generated by this script.  Real
data comparisons should use the same result schema once the local HDF5 products
are available in this worktree.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import statistics
import subprocess
import sys
import tarfile
import tempfile
import time
from pathlib import Path
from typing import Any

import h5py
import numpy as np
import yaml


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_ROOT = PROJECT_ROOT / "Bayesian_inference" / "docs" / "reports" / "main_comparison"


def parse_args() -> argparse.Namespace:
    """Parse the branch comparison command line."""

    parser = argparse.ArgumentParser(description="Compare current CMASS log_prob against main.")
    parser.add_argument("--main-ref", default="main", help="Git ref used as the main comparison target.")
    parser.add_argument(
        "--candidate-root",
        default=str(PROJECT_ROOT),
        help="Candidate repository root. Defaults to the current worktree.",
    )
    parser.add_argument("--case", default="cmass_synthetic_sersic", choices=["cmass_synthetic_sersic"])
    parser.add_argument("--repeats", type=int, default=20, help="Steady-state log_prob repeats per branch.")
    parser.add_argument("--numba-threads", type=int, default=1, help="Numba thread count for child processes.")
    parser.add_argument(
        "--theta-axis-points",
        type=int,
        default=65537,
        help="Canonical theta_E grid points for the synthetic cross-section table.",
    )
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_ROOT),
        help="Directory where comparison JSON and summary markdown are written.",
    )
    return parser.parse_args()


def _write_raw_hunit_observation(path: Path) -> None:
    """Write one raw h-units observation file that both branches can map."""

    gamma_grid = np.linspace(1.3, 2.7, 17)
    mass_grid = np.linspace(11.7, 10.9, 17)
    dmass_dthetaein_grid = np.linspace(-2.0, -1.0, 17)
    s2_grid = np.linspace(0.8, 1.2, 17)

    with h5py.File(path, "w") as handle:
        handle.attrs["unit_convention"] = "h_units_v1"
        handle.attrs["h_ref"] = 0.7
        group = handle.create_group("lens-hunit")
        group.attrs["unit_convention"] = "h_units_v1"
        group.attrs["h_ref"] = 0.7
        group.attrs["zd"] = 0.55
        group.attrs["zs"] = 1.75
        group.attrs["logmchab_h2"] = 10.99
        group.attrs["logmchab_err"] = 0.05
        group.attrs["log10_re_hinv_kpc"] = 0.64
        group.attrs["nser"] = 4.2
        group.attrs["rein_arcsec"] = 1.3
        group.attrs["num_sigma"] = 1
        group.attrs["sigma"] = 320000.0
        group.attrs["sigma_err"] = 20000.0
        group.create_dataset("gamma_grid", data=gamma_grid)
        mass_group = group.create_group("mass_definitions").create_group("m5_hinvkpc")
        mass_group.attrs["unit_convention"] = "h_units_v1"
        mass_group.attrs["h_ref"] = 0.7
        mass_group.create_dataset("mass_grid", data=mass_grid)
        mass_group.create_dataset("dmass_dthetaein_grid", data=dmass_dthetaein_grid)
        mass_group.create_dataset("s2_grid", data=s2_grid)


def _write_raw_cross_section(path: Path) -> None:
    """Write the raw cross-section grid shape used by the main branch."""

    with h5py.File(path, "w") as handle:
        group = handle.create_group("compressed_grids")
        group.create_dataset("gamma_grids", data=np.linspace(1.3, 2.7, 17))
        # Keep the synthetic consistency case independent of gamma-direction
        # interpolation details.  The real-data case can still exercise the
        # full finite-grid contract once the local HDF5 products are present.
        group.create_dataset("cs_over_theta_ein_grid", data=np.ones(17, dtype=float))


def _write_candidate_canonical_dataset(path: Path, *, theta_axis_points: int) -> None:
    """Write the candidate branch's canonical equivalent of the synthetic case."""

    gamma_grid = np.linspace(1.3, 2.7, 17)
    theta_e_axis = np.linspace(0.0, 5.0, max(64, int(theta_axis_points)))
    cs_over_theta = np.ones(gamma_grid.size, dtype=float)
    string_dtype = h5py.string_dtype(encoding="utf-8")

    with h5py.File(path, "w") as handle:
        metadata = handle.create_group("metadata")
        metadata.attrs["schema_version"] = "canonical_inference_dataset_v1"
        metadata.attrs["unit_convention"] = "h_units_v1"
        metadata.attrs["h_ref"] = 0.7
        metadata.attrs["profile_name"] = "sersic"
        metadata.attrs["mass_definition_label"] = "m5_hinvkpc"
        metadata.attrs["mass_radius_kpc"] = 5.0
        metadata.attrs["cosmology_h0"] = 70.0
        metadata.attrs["cosmology_omega_m"] = 0.3
        metadata.create_dataset(
            "capabilities",
            data=np.asarray(
                [
                    "lens_observations.v1",
                    "lensing_mass_grids.v1",
                    "lensing_cross_section.theta_gamma_grid.v1",
                    "velocity_dispersion.per_lens_s2.v1",
                ],
                dtype=object,
            ),
            dtype=string_dtype,
        )

        lenses = handle.create_group("lenses")
        lenses.create_dataset("lens_id", data=np.asarray(["lens-hunit"], dtype=object), dtype=string_dtype)
        lenses.create_dataset("z_d", data=np.asarray([0.55], dtype=float))
        lenses.create_dataset("z_s", data=np.asarray([1.75], dtype=float))
        lenses.create_dataset("log_mstar_obs", data=np.asarray([10.99], dtype=float))
        lenses.create_dataset("log_mstar_err", data=np.asarray([0.05], dtype=float))
        lenses.create_dataset("log_re_obs", data=np.asarray([0.64], dtype=float))
        lenses.create_dataset("n_obs", data=np.asarray([4.2], dtype=float))
        lenses.create_dataset("theta_e_obs", data=np.asarray([1.3], dtype=float))
        lenses.create_dataset("num_sigma", data=np.asarray([1], dtype=np.int64))
        lenses.create_dataset("sigma_obs", data=np.asarray([[320000.0, 0.0]], dtype=float))
        lenses.create_dataset("sigma_err", data=np.asarray([[20000.0, 1.0]], dtype=float))

        mass_grids = handle.create_group("lensing_mass_grids")
        mass_grids.create_dataset("gamma_grid", data=gamma_grid[None, :])
        mass_grids.create_dataset("log_enclosed_mass_grid", data=np.linspace(11.7, 10.9, 17)[None, :])
        mass_grids.create_dataset("dmass_dthetaein_grid", data=np.linspace(-2.0, -1.0, 17)[None, :])
        mass_grids.create_dataset("s2_grid", data=np.linspace(0.8, 1.2, 17)[None, :])
        mass_grids.create_dataset("has_s2", data=np.asarray([1], dtype=np.int64))

        cross_section = handle.create_group("lensing_cross_section")
        cross_section.create_dataset("theta_e_axis", data=theta_e_axis)
        cross_section.create_dataset("gamma_axis", data=gamma_grid)
        cross_section.create_dataset(
            "cross_section_grid",
            data=np.pi * (theta_e_axis[:, None] * cs_over_theta[None, :]) ** 2,
        )
        cross_section.attrs["boundary_policy"] = "zero_outside_theta_clip_gamma"

        velocity = handle.create_group("velocity_dispersion_grids")
        per_lens_s2 = velocity.create_group("per_lens_s2")
        per_lens_s2.create_dataset("s2_grid", data=np.linspace(0.8, 1.2, 17)[None, :])
        per_lens_s2.create_dataset("has_s2", data=np.asarray([1], dtype=np.int64))


def _shared_sampling_center() -> dict[str, float]:
    """Return the shared h-units CMASS initial point for both branches."""

    return {
        "mu5h_0": 11.17,
        "beta5h": 0.59,
        "xi5h": -0.11,
        "sigma5h": 0.06,
        "mu_gamma_0": 1.99,
        "beta_sigma_star_gamma": 0.24,
        "sigma_gamma": 0.149,
        "mu_zs": 1.8,
        "sigma_zs": 0.215,
        "theta0": 0.93,
        "loga": 1.0,
    }


def _shared_box_prior() -> dict[str, list[float]]:
    """Return the shared h-units CMASS box prior."""

    return {
        "mu5h_0": [9.0, 12.0],
        "beta5h": [-3.0, 3.0],
        "xi5h": [-3.0, 3.0],
        "sigma5h": [1.0e-2, 0.2],
        "mu_gamma_0": [1.5, 2.5],
        "beta_sigma_star_gamma": [-3.0, 3.0],
        "sigma_gamma": [0.0, 0.5],
        "mu_zs": [1.0, 3.0],
        "sigma_zs": [0.0, 2.0],
        "theta0": [0.0, 3.0],
        "loga": [-1.0, 3.0],
    }


def write_synthetic_case(case_dir: Path, *, theta_axis_points: int = 65537) -> dict[str, Path]:
    """Create raw and canonical inputs plus branch-specific YAML configs."""

    case_dir.mkdir(parents=True, exist_ok=True)
    raw_observation_path = case_dir / "synthetic_hunit_observations.hdf5"
    raw_cross_section_path = case_dir / "synthetic_cs_grid_power.h5"
    canonical_dataset_path = case_dir / "synthetic_canonical.hdf5"
    _write_raw_hunit_observation(raw_observation_path)
    _write_raw_cross_section(raw_cross_section_path)
    _write_candidate_canonical_dataset(canonical_dataset_path, theta_axis_points=theta_axis_points)

    common_runtime = {
        "checkpoint_every": 1,
        "parallel_strategy": "off",
        "progress": False,
        "progress_summary_every": 1,
        "show_stage_timing": False,
        "disable_hdf5_file_locking": False,
        "num_threads": 1,
        "reserve_cores": 0,
    }
    main_config = {
        "profile": {"name": "sersic"},
        "unit_convention": "h_units_v1",
        "mass_definition": {"aperture_hinv_kpc": 5},
        "gamma_model": {"mode": "sigma_star_dependent"},
        "data": {
            "observation_path": str(raw_observation_path),
            "cross_section_path": str(raw_cross_section_path),
        },
        "box_prior": _shared_box_prior(),
        "sampling": {
            "random_seed": 7,
            "n_walkers": 24,
            "n_steps": 3,
            "warmup": 1,
            "initial_center": _shared_sampling_center(),
            "initial_jitter_scale": 1.0e-3,
        },
        "integration": {"gamma_points": 80, "mstar_points": 80, "normalization_samples": 256},
        "cosmology": {"h0": 70.0, "omega_m": 0.3},
        "runtime": common_runtime,
        "output": {
            "root_dir": str(case_dir / "main_outputs"),
            "run_label": "main-synthetic",
            "overwrite_latest": True,
        },
    }
    candidate_config = {
        "profile": {"name": "sersic"},
        "unit_convention": "h_units_v1",
        "model": {"name": "cmass"},
        "data": {"inference_dataset_path": str(canonical_dataset_path)},
        "box_prior": _shared_box_prior(),
        "sampling": {
            "random_seed": 7,
            "n_walkers": 24,
            "n_steps": 3,
            "burn_in": 1,
            "initial_center": _shared_sampling_center(),
            "initial_jitter_scale": 1.0e-3,
        },
        "integration": {"gamma_points": 80, "mstar_points": 80, "normalization_samples": 256},
        "cosmology": {"h0": 70.0, "omega_m": 0.3},
        "runtime": common_runtime,
        "output": {
            "root_dir": str(case_dir / "candidate_outputs"),
            "run_label": "candidate-synthetic",
            "overwrite_latest": True,
        },
    }

    main_config_path = case_dir / "main_config.yaml"
    candidate_config_path = case_dir / "candidate_config.yaml"
    main_config_path.write_text(yaml.safe_dump(main_config, sort_keys=False), encoding="utf-8")
    candidate_config_path.write_text(yaml.safe_dump(candidate_config, sort_keys=False), encoding="utf-8")
    return {
        "main_config": main_config_path,
        "candidate_config": candidate_config_path,
        "raw_observation": raw_observation_path,
        "raw_cross_section": raw_cross_section_path,
        "canonical_dataset": canonical_dataset_path,
    }


def normalize_branch_result(result: dict[str, Any]) -> dict[str, float]:
    """Reduce one branch subprocess result to stable comparison fields."""

    log_prob_value = result.get("steady_log_prob_value", result.get("log_prob_value"))
    normalization_value = result.get("steady_normalization_value", result.get("normalization_value"))
    if log_prob_value is None or normalization_value is None:
        raise KeyError("Branch result must contain steady or normalized log_prob and normalization values.")

    return {
        "first_call_seconds": float(result["first_call_seconds"]),
        "first_log_prob_value": float(result.get("first_log_prob_value", log_prob_value)),
        "first_normalization_value": float(result.get("first_normalization_value", normalization_value)),
        "log_prob_value": float(log_prob_value),
        "normalization_value": float(normalization_value),
        "steady_log_prob_median_seconds": float(result["steady_log_prob_median_seconds"]),
        "steady_log_prob_min_seconds": float(result["steady_log_prob_min_seconds"]),
        "steady_log_prob_mean_seconds": float(result["steady_log_prob_mean_seconds"]),
    }


def build_comparison_payload(
    *,
    case_name: str,
    main_git_hash: str,
    candidate_git_hash: str,
    main_result: dict[str, Any],
    candidate_result: dict[str, Any],
    environment: dict[str, Any],
) -> dict[str, Any]:
    """Build the machine-readable comparison payload."""

    main_normalized = normalize_branch_result(main_result)
    candidate_normalized = normalize_branch_result(candidate_result)
    main_time = main_normalized["steady_log_prob_median_seconds"]
    candidate_time = candidate_normalized["steady_log_prob_median_seconds"]
    speed_ratio = candidate_time / main_time if main_time > 0.0 else math.nan

    return {
        "case_name": case_name,
        "main_git_hash": main_git_hash,
        "candidate_git_hash": candidate_git_hash,
        "environment": environment,
        "main": main_normalized,
        "candidate": candidate_normalized,
        "comparison": {
            "log_prob_abs_diff": abs(candidate_normalized["log_prob_value"] - main_normalized["log_prob_value"]),
            "normalization_abs_diff": abs(
                candidate_normalized["normalization_value"] - main_normalized["normalization_value"]
            ),
            "steady_speed_ratio_candidate_over_main": float(speed_ratio),
        },
    }


def _git_output(args: list[str], cwd: Path) -> str:
    """Run a git command and return stripped stdout."""

    return subprocess.check_output(["git", *args], cwd=str(cwd), text=True).strip()


def _export_git_ref(repo_root: Path, ref: str, destination: Path) -> Path:
    """Export one git ref into a plain directory without touching worktrees."""

    destination.mkdir(parents=True, exist_ok=True)
    marker = destination / ".archive_complete"
    if marker.exists():
        return destination

    with tempfile.TemporaryFile() as archive_file:
        subprocess.run(
            ["git", "archive", "--format=tar", ref],
            cwd=str(repo_root),
            stdout=archive_file,
            check=True,
        )
        archive_file.seek(0)
        with tarfile.open(fileobj=archive_file, mode="r:") as archive:
            archive.extractall(destination)
    marker.write_text(ref, encoding="utf-8")
    return destination


def _branch_runner_code() -> str:
    """Return the Python code executed inside each isolated branch subprocess."""

    return r'''
from __future__ import annotations

import json
import os
import statistics
import sys
import time
from pathlib import Path

source_root = Path(sys.argv[1]).resolve() / "Bayesian_inference" / "src"
config_path = Path(sys.argv[2]).resolve()
api_kind = sys.argv[3]
repeats = int(sys.argv[4])

if str(source_root) not in sys.path:
    sys.path.insert(0, str(source_root))

from cmass_lens_inference.config import load_runtime_config

if api_kind == "main":
    from cmass_lens_inference.model import build_compiled_model, log_prob
elif api_kind == "candidate":
    from cmass_lens_inference.numba_backend.likelihood_engine import build_compiled_model, log_prob
else:
    raise ValueError(f"Unknown api_kind: {api_kind}")

runtime_config = load_runtime_config(config_path)
compiled_model = build_compiled_model(runtime_config)
theta = runtime_config.sampling.initial_center.to_array()

first_started = time.perf_counter()
first_value, first_blob = log_prob(theta, compiled_model)
first_seconds = time.perf_counter() - first_started

times = []
values = []
normalizations = []
for _ in range(max(1, repeats)):
    started = time.perf_counter()
    value, blob = log_prob(theta, compiled_model)
    times.append(time.perf_counter() - started)
    values.append(float(value))
    normalizations.append(float(blob["normalization_value"]))

print(json.dumps({
    "first_call_seconds": float(first_seconds),
    "first_log_prob_value": float(first_value),
    "first_normalization_value": float(first_blob["normalization_value"]),
    "steady_log_prob_median_seconds": float(statistics.median(times)),
    "steady_log_prob_min_seconds": float(min(times)),
    "steady_log_prob_mean_seconds": float(statistics.mean(times)),
    "steady_log_prob_value": float(values[-1]),
    "steady_normalization_value": float(normalizations[-1]),
    "repeats": int(repeats),
    "api_kind": api_kind,
    "omp_max_active_levels": os.environ.get("OMP_MAX_ACTIVE_LEVELS", ""),
    "numba_num_threads": os.environ.get("NUMBA_NUM_THREADS", ""),
}))
'''


def _run_branch_benchmark(
    *,
    branch_root: Path,
    config_path: Path,
    api_kind: str,
    repeats: int,
    numba_threads: int,
) -> dict[str, Any]:
    """Run one branch benchmark in a clean subprocess and parse its JSON."""

    env = os.environ.copy()
    env["PYTHONPATH"] = str(branch_root / "Bayesian_inference" / "src")
    env["OMP_MAX_ACTIVE_LEVELS"] = "1"
    env["KMP_WARNINGS"] = "0"
    env["NUMBA_NUM_THREADS"] = str(max(1, int(numba_threads)))
    env["OPENBLAS_NUM_THREADS"] = "1"
    env["MKL_NUM_THREADS"] = "1"
    completed = subprocess.run(
        [
            sys.executable,
            "-c",
            _branch_runner_code(),
            str(branch_root),
            str(config_path),
            api_kind,
            str(repeats),
        ],
        cwd=str(branch_root),
        env=env,
        text=True,
        capture_output=True,
        check=True,
    )
    return json.loads(completed.stdout)


def _write_summary_markdown(path: Path, payload: dict[str, Any]) -> None:
    """Write a compact human-readable summary next to the JSON artifact."""

    comparison = payload["comparison"]
    lines = [
        "# Main Comparison Summary",
        "",
        f"- case: `{payload['case_name']}`",
        f"- main hash: `{payload['main_git_hash']}`",
        f"- candidate hash: `{payload['candidate_git_hash']}`",
        f"- log_prob abs diff: `{comparison['log_prob_abs_diff']}`",
        f"- normalization abs diff: `{comparison['normalization_abs_diff']}`",
        f"- candidate/main steady median ratio: `{comparison['steady_speed_ratio_candidate_over_main']}`",
        "",
        "| branch | log_prob | normalization | first_call_s | steady_median_s | steady_min_s | steady_mean_s |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for key in ("main", "candidate"):
        row = payload[key]
        lines.append(
            f"| {key} | {row['log_prob_value']} | {row['normalization_value']} | "
            f"{row['first_call_seconds']} | {row['steady_log_prob_median_seconds']} | "
            f"{row['steady_log_prob_min_seconds']} | {row['steady_log_prob_mean_seconds']} |"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    """Run the branch-aware comparison and write JSON plus Markdown outputs."""

    args = parse_args()
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    candidate_root = Path(args.candidate_root).expanduser().resolve()
    main_hash = _git_output(["rev-parse", args.main_ref], cwd=PROJECT_ROOT)
    candidate_hash = _git_output(["rev-parse", "HEAD"], cwd=candidate_root)
    with tempfile.TemporaryDirectory(prefix="cmass_main_compare_") as temporary_root_text:
        temporary_root = Path(temporary_root_text)
        case_paths = write_synthetic_case(
            temporary_root / "case_inputs" / args.case,
            theta_axis_points=args.theta_axis_points,
        )
        main_root = _export_git_ref(
            PROJECT_ROOT,
            args.main_ref,
            temporary_root / "branch_exports" / f"main_{main_hash[:12]}",
        )

        main_result = _run_branch_benchmark(
            branch_root=main_root,
            config_path=case_paths["main_config"],
            api_kind="main",
            repeats=args.repeats,
            numba_threads=args.numba_threads,
        )
        candidate_result = _run_branch_benchmark(
            branch_root=candidate_root,
            config_path=case_paths["candidate_config"],
            api_kind="candidate",
            repeats=args.repeats,
            numba_threads=args.numba_threads,
        )

    payload = build_comparison_payload(
        case_name=args.case,
        main_git_hash=main_hash,
        candidate_git_hash=candidate_hash,
        main_result=main_result,
        candidate_result=candidate_result,
        environment={
            "python": sys.version.split()[0],
            "numba_threads": int(args.numba_threads),
            "omp_max_active_levels": "1",
            "theta_axis_points": int(args.theta_axis_points),
        },
    )
    json_path = output_dir / f"{args.case}_comparison.json"
    summary_path = output_dir / f"{args.case}_summary.md"
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    _write_summary_markdown(summary_path, payload)
    print(json.dumps({"comparison_path": str(json_path), "summary_path": str(summary_path), **payload}, indent=2))


if __name__ == "__main__":
    main()
